version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      # specify the version you desire here
      - image: starefossen/ruby-node:alpine

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/repo
    enviroments:
      BUNDLE_PATH: ~repos/vendor/bundle
    steps:
      - run:
          name: Prepare system denpendencies
          command: |
            uname -r
            echo "ipv6" >> /etc/modules
            apk update
            apk add --no-cache perl-image-exiftool git openssh python make gcc g++
            apk update

      - run:
          name: Clone
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone git@github.com:thai-hq/huetri.com.git ~/repo
            cd ~/repo

      - run:
          name: Check file
          command: ls -al && git status

      - run: gem install bundler

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - run: bundle install --path $BUNDLE_PATH

      - save_cache:
          paths:
            - ~repos/vendor/bundle
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Build
          command: yarn build

      - run:
          name: Deploy to Github Pages
          command: |
            git config --local user.name="Hoang Dan An (CircleCI)"
            git config --local user.email="beohoang98@noreply.users.github.com"
            yarn deploy_old
