---
new_page_extension: md
auto_deploy: true
admin_path: admin
webhook_url: https://discordapp.com/api/webhooks/564480707800596500/b9WTjNJ_yjHJkg1now2PWyTdfKNDZGKMP5S91j3cNyvkttDwPxqIwqstUf6c1CPlTFej
sections:
- type: directory
  path: _pages
  label: Pages
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: _gallery
  label: Gallery
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - gallery
- type: directory
  path: _drafts
  label: Drafts
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - post
- type: heading
  label: Developer Section
- type: jekyll-pages
  label: Pages
  create: documents
- type: directory
  path: wp-content/uploads
  label: Images
  create: all
  match: "**/*"
  new_doc_ext: "*"
upload_dir: wp-content/uploads
public_path: "/wp-content/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
instant_preview: 
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  publish_command: bundle exec jekyll build -d _site --baseurl=''
  publish_env:
  - JEKYLL_ENV=production
  output_directory: _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
